'use client';

import React, { useState, useEffect } from 'react';
import { useCategories, Category } from '@/app/context/categoryContext';
import { 
  Dialog, 
  DialogContent, 
  DialogHeader, 
  DialogTitle, 
  DialogFooter 
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Switch } from '@/components/ui/switch';
import { Badge } from '@/components/ui/badge';
import { X } from 'lucide-react';

interface CategoryFormProps {
  isOpen: boolean;
  onClose: () => void;
  category?: Category;
}

export default function CategoryForm({ isOpen, onClose, category }: CategoryFormProps) {
  const { addCategory, updateCategory } = useCategories();
  const [isEditing, setIsEditing] = useState(false);
  
  const [formData, setFormData] = useState<Omit<Category, 'category_id' | 'spent'> & { category_id?: string, spent?: number }>({
    category_name: '',
    category_description: '',
    tags: [],
    image: '/login.jpg',
    budget: 0,
    spent: 0,
    predefined: false,
    color: 'cyan',
    recurring: false,
  });
  
  const [tagInput, setTagInput] = useState('');

  useEffect(() => {
    if (category) {
      setFormData({
        category_id: category.category_id,
        category_name: category.category_name,
        category_description: category.category_description,
        tags: category.tags,
        image: category.image,
        budget: category.budget,
        spent: category.spent,
        predefined: category.predefined,
        color: category.color,
        recurring: category.recurring,
      });
      setIsEditing(true);
    } else {
      setFormData({
        category_name: '',
        category_description: '',
        tags: [],
        image: '/login.jpg',
        budget: 0,
        spent: 0,
        predefined: false,
        color: 'cyan',
        recurring: false,
      });
      setIsEditing(false);
    }
  }, [category, isOpen]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleNumberChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: parseFloat(value) || 0 }));
  };

  const handleSwitchChange = (name: string, checked: boolean) => {
    setFormData(prev => ({ ...prev, [name]: checked }));
  };

  const handleAddTag = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter' && tagInput.trim()) {
      e.preventDefault();
      setFormData(prev => ({
        ...prev,
        tags: [...prev.tags, tagInput.trim()]
      }));
      setTagInput('');
    }
  };

  const handleRemoveTag = (tagToRemove: string) => {
    setFormData(prev => ({
      ...prev,
      tags: prev.tags.filter(tag => tag !== tagToRemove)
    }));
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    if (isEditing && formData.category_id) {
      updateCategory({
        category_id: formData.category_id,
        category_name: formData.category_name,
        category_description: formData.category_description,
        tags: formData.tags,
        image: formData.image,
        budget: formData.budget,
        spent: formData.spent || 0,
        predefined: formData.predefined,
        color: formData.color,
        recurring: formData.recurring,
      });
    } else {
      addCategory({
        category_id: '', // This will be generated by the backend
        category_name: formData.category_name,
        category_description: formData.category_description,
        tags: formData.tags,
        image: formData.image,
        budget: formData.budget,
        spent: 0,
        predefined: formData.predefined,
        color: formData.color,
        recurring: formData.recurring,
      });
    }
    
    onClose();
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-[600px]">
        <DialogHeader>
          <DialogTitle>{isEditing ? 'Edit Category' : 'Add New Category'}</DialogTitle>
        </DialogHeader>
        
        <form onSubmit={handleSubmit} className="space-y-6">
          <div className="grid grid-cols-1 gap-4">
            <div className="space-y-2">
              <Label htmlFor="category_name">Category Name</Label>
              <Input
                id="category_name"
                name="category_name"
                value={formData.category_name}
                onChange={handleChange}
                required
              />
            </div>
            
            <div className="space-y-2">
              <Label htmlFor="category_description">Description</Label>
              <Textarea
                id="category_description"
                name="category_description"
                value={formData.category_description}
                onChange={handleChange}
                rows={3}
              />
            </div>
            
            <div className="space-y-2">
              <Label htmlFor="budget">Budget Amount</Label>
              <Input
                id="budget"
                name="budget"
                type="number"
                min="0"
                step="0.01"
                value={formData.budget}
                onChange={handleNumberChange}
                required
              />
            </div>
            
            <div className="space-y-2">
              <Label htmlFor="image">Image URL</Label>
              <Input
                id="image"
                name="image"
                value={formData.image}
                onChange={handleChange}
                placeholder="/login.jpg"
              />
            </div>
            
            <div className="space-y-2">
              <Label htmlFor="tags">Tags (press Enter to add)</Label>
              <Input
                id="tags"
                value={tagInput}
                onChange={(e) => setTagInput(e.target.value)}
                onKeyDown={handleAddTag}
                placeholder="Add a tag..."
              />
              <div className="flex flex-wrap gap-2 mt-2">
                {formData.tags.map((tag, index) => (
                  <Badge key={index} className="flex items-center gap-1 px-3 py-1">
                    {tag}
                    <button 
                      type="button" 
                      onClick={() => handleRemoveTag(tag)}
                      className="ml-1 rounded-full hover:bg-gray-200 p-1"
                    >
                      <X size={12} />
                    </button>
                  </Badge>
                ))}
              </div>
            </div>
            
            <div className="flex items-center justify-between">
              <Label htmlFor="recurring">Recurring</Label>
              <Switch
                id="recurring"
                checked={formData.recurring}
                onCheckedChange={(checked) => handleSwitchChange('recurring', checked)}
              />
            </div>
            
            <div className="flex items-center justify-between">
              <Label htmlFor="predefined">Predefined</Label>
              <Switch
                id="predefined"
                checked={formData.predefined}
                onCheckedChange={(checked) => handleSwitchChange('predefined', checked)}
              />
            </div>
          </div>
          
          <DialogFooter>
            <Button type="button" variant="outline" onClick={onClose}>
              Cancel
            </Button>
            <Button type="submit">
              {isEditing ? 'Update' : 'Create'} Category
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
} 